<?php

namespace App\Services\Integration;

use App\Enums\FastApiStatus;
use Illuminate\Http\Client\ConnectionException;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Throwable;

/**
 * Thin client for the internal FastAPI (AI/CV) service.
 *
 * FastAPI only provides facts (face verification, liveness, model inference,
 * etc.). Laravel remains the business authority and decides what those facts
 * mean for the business process.
 */
class FastApiService
{
    /**
     * Resolve the base URL of the FastAPI service.
     */
    public function baseUrl(): string
    {
        return rtrim((string) config('services.fastapi.base_url', 'http://127.0.0.1:8001'), '/');
    }

    /**
     * Resolve the request timeout (seconds).
     */
    public function timeout(): int
    {
        return (int) config('services.fastapi.timeout', 5);
    }

    /**
     * Resolve the API key used to authenticate FastAPI requests.
     */
    public function apiKey(): string
    {
        $key = (string) config('services.fastapi.api_key', '');

        if ($key === '' && ! app()->environment('local', 'testing')) {
            throw new \RuntimeException('FastAPI API key is not configured. Set FASTAPI_API_KEY in non-local environments.');
        }

        return $key;
    }

    /**
     * Build a base HTTP client request with auth and timeout.
     */
    private function client()
    {
        return Http::timeout($this->timeout())
            ->acceptJson()
            ->withHeaders([
                'X-API-Key' => $this->apiKey(),
            ]);
    }

    /**
     * Ping the FastAPI health endpoint.
     *
     * Failures are represented explicitly through FastApiStatus and are never
     * silently mapped to a successful result.
     *
     * @return array{status: FastApiStatus, health: array<string, mixed>|null}
     */
    public function health(): array
    {
        try {
            $response = $this->client()->get($this->baseUrl().'/health');
        } catch (ConnectionException $e) {
            return [
                'status' => $this->resolveConnectionFailure($e),
                'health' => null,
            ];
        } catch (Throwable) {
            return [
                'status' => FastApiStatus::Unavailable,
                'health' => null,
            ];
        }

        if (! $response->successful()) {
            return [
                'status' => FastApiStatus::InvalidResponse,
                'health' => null,
            ];
        }

        $payload = $response->json();

        if (! is_array($payload)) {
            return [
                'status' => FastApiStatus::InvalidResponse,
                'health' => null,
            ];
        }

        return [
            'status' => FastApiStatus::Available,
            'health' => $payload,
        ];
    }

    /**
     * Enroll a face image.
     *
     * Laravel remains responsible for employee identity. FastAPI only receives
     * the image and an idempotency key that identifies this enrollment operation.
     *
     * @param  string  $idempotencyKey  UUIDv4 generated by Laravel.
     * @param  string  $imagePath  Absolute path to the face image file.
     * @param  string|null  $mimeType  Optional MIME type; inferred from path if omitted.
     * @return array{status: FastApiStatus, data: array{enrolled: bool, model_version: string, embedding_reference: string, face_detected: bool, quality: array, liveness: array, processing_time_ms: float}|null, error: string|null}
     */
    public function enroll(string $idempotencyKey, string $imagePath, ?string $mimeType = null): array
    {
        return $this->callEndpoint('/face/enroll', [
            'idempotency_key' => $idempotencyKey,
        ], $imagePath, $mimeType);
    }

    /**
     * Verify a probe face image against the enrolled embedding for an employee.
     *
     * @param  string  $employeeId  Employee identifier (employee_code).
     * @param  string  $imagePath  Absolute path to the probe face image file.
     * @param  string|null  $embeddingReference  Optional opaque reference from enrollment.
     * @param  string|null  $mimeType  Optional MIME type; inferred from path if omitted.
     * @return array{status: FastApiStatus, data: array{verified: bool, confidence: float, liveness: bool, liveness_reason: string|null, face_detected: bool, model_version: string, processing_time_ms: int, quality_score: float}|null, error: string|null}
     */
    public function verify(string $employeeId, string $imagePath, ?string $embeddingReference = null, ?string $mimeType = null): array
    {
        $formFields = [
            'employee_id' => $employeeId,
        ];

        if ($embeddingReference !== null) {
            $formFields['embedding_reference'] = $embeddingReference;
        }

        return $this->callEndpoint('/face/verify', $formFields, $imagePath, $mimeType);
    }

    /**
     * Delete a stored embedding by its opaque reference.
     *
     * Used for compensation when Laravel persistence fails after FastAPI
     * successfully stored the embedding.
     *
     * @param  string  $embeddingReference  Opaque embedding reference returned by FastAPI.
     * @return array{status: FastApiStatus, deleted: bool, error: string|null}
     */
    public function deleteEmbedding(string $embeddingReference): array
    {
        try {
            $response = $this->client()
                ->asMultipart()
                ->delete($this->baseUrl().'/face/embeddings/'.urlencode($embeddingReference));
        } catch (ConnectionException $e) {
            Log::channel('stack')->warning('FastAPI delete connection failure.', [
                'embedding_reference' => $embeddingReference,
                'exception' => $e,
            ]);

            return [
                'status' => $this->resolveConnectionFailure($e),
                'deleted' => false,
                'error' => 'AI service unavailable.',
            ];
        } catch (Throwable $e) {
            Log::channel('stack')->warning('FastAPI delete request failed.', [
                'embedding_reference' => $embeddingReference,
                'exception' => $e,
            ]);

            return [
                'status' => FastApiStatus::Unavailable,
                'deleted' => false,
                'error' => 'AI service unavailable.',
            ];
        }

        if ($response->status() === 404) {
            return [
                'status' => FastApiStatus::Available,
                'deleted' => false,
                'error' => 'Embedding reference not found.',
            ];
        }

        if ($response->status() === 204) {
            return [
                'status' => FastApiStatus::Available,
                'deleted' => true,
                'error' => null,
            ];
        }

        if ($response->status() === 401) {
            return [
                'status' => FastApiStatus::InvalidResponse,
                'deleted' => false,
                'error' => 'AI service authentication failed.',
            ];
        }

        return [
            'status' => FastApiStatus::InvalidResponse,
            'deleted' => false,
            'error' => 'Unexpected response from AI service.',
        ];
    }

    /**
     * Common endpoint caller for enroll/verify.
     *
     * @param  string  $endpoint  /face/enroll or /face/verify
     * @param  array<string, string>  $formFields
     * @return array{status: FastApiStatus, data: array<string, mixed>|null, error: string|null}
     */
    private function callEndpoint(string $endpoint, array $formFields, string $imagePath, ?string $mimeType = null): array
    {
        $mimeType = $mimeType ?? $this->inferMimeType($imagePath);
        $filename = basename($imagePath);

        try {
            $response = $this->client()
                ->attach('image', file_get_contents($imagePath), $filename, [
                    'Content-Type' => $mimeType,
                ])
                ->asMultipart()
                ->post($this->baseUrl().$endpoint, $formFields);
        } catch (ConnectionException $e) {
            Log::channel('stack')->warning('FastAPI connection failure.', [
                'endpoint' => $endpoint,
                'exception' => $e,
            ]);

            return [
                'status' => $this->resolveConnectionFailure($e),
                'data' => null,
                'error' => 'AI service unavailable.',
            ];
        } catch (Throwable $e) {
            Log::channel('stack')->warning('FastAPI request failed.', [
                'endpoint' => $endpoint,
                'exception' => $e,
            ]);

            return [
                'status' => FastApiStatus::Unavailable,
                'data' => null,
                'error' => 'AI service unavailable.',
            ];
        }

        if (! $response->successful()) {
            $status = $response->status();

            if ($status === 401) {
                return [
                    'status' => FastApiStatus::InvalidResponse,
                    'data' => null,
                    'error' => 'AI service authentication failed.',
                ];
            }

            if ($status === 503) {
                return [
                    'status' => FastApiStatus::Unavailable,
                    'data' => null,
                    'error' => 'AI service unavailable.',
                ];
            }

            if ($status === 409) {
                return [
                    'status' => FastApiStatus::Conflict,
                    'data' => null,
                    'error' => 'Enrollment conflict. Please try again.',
                ];
            }

            if (in_array($status, [400, 422], true)) {
                return [
                    'status' => FastApiStatus::InvalidResponse,
                    'data' => null,
                    'error' => 'Invalid face image.',
                ];
            }

            return [
                'status' => FastApiStatus::InvalidResponse,
                'data' => null,
                'error' => 'Unexpected response from AI service.',
            ];
        }

        $payload = $response->json();

        if (! is_array($payload)) {
            return [
                'status' => FastApiStatus::InvalidResponse,
                'data' => null,
                'error' => 'Unexpected response from AI service.',
            ];
        }

        return [
            'status' => FastApiStatus::Available,
            'data' => $payload,
            'error' => null,
        ];
    }

    /**
     * Infer MIME type from file extension.
     */
    private function inferMimeType(string $path): string
    {
        $ext = strtolower(pathinfo($path, PATHINFO_EXTENSION));

        return match ($ext) {
            'jpg', 'jpeg' => 'image/jpeg',
            'png' => 'image/png',
            'webp' => 'image/webp',
            default => 'application/octet-stream',
        };
    }

    /**
     * Distinguish a slow/timeout failure from an unreachable service.
     */
    private function resolveConnectionFailure(ConnectionException $exception): FastApiStatus
    {
        $message = strtolower($exception->getMessage());

        if (str_contains($message, 'timed out') || str_contains($message, 'timeout')) {
            return FastApiStatus::Timeout;
        }

        return FastApiStatus::Unavailable;
    }
}
